### ISSUE TITLE
About the splicing of 4 pictures

### ISSUE THREAD

**Issue by tigerdhl** [neozhaoliang/surround-view-system-introduction#80]
Thank you for sharing. But there is a question that I don’t understand. For example, when splicing two images, top and left, how the grids can be aligned neatly, the usual method is through feature matching, but the author does not seem to mention this step, only smoothing the splicing after the splicing is completed.
@neozhaoliang

**Comment by neozhaoliang** [comment]
Sorry I don't know much about feature matching. Do you think it can stitch the images in real time?

**Comment by tigerdhl** [comment]
> Sorry I don't know much about feature matching. Do you think it can stitch the images in real time?

What I mean is how the two fisheye correction images from adjacent cameras are spliced ​​together. I see that your documentation directly talks about the transition problem after splicing.

**Comment by neozhaoliang** [comment]
They can match together because, at the projection calibration step, you specified the parameters to project the images.

**Comment by tigerdhl** [comment]
> They can match together because, at the projection calibration step, you specified the parameters to project the images.

ok,I get it. For example,the four pixel points in the BEV image is Well designed？

**Comment by neozhaoliang** [comment]
You need to choose >=4 points to make sure your projected image covers the right region on the ground. The feature-matching method should also work as long as it can give the correct projection matrix. However, I'm not sure how well it behaves because the projected images are taken by the front and left cameras respectively, they are not taken by the same camera from different view points. So I doubt more advanced method should be used here.
